### ISSUE TITLE
Lifetime problems with AudioCallbackHandle

### ISSUE THREAD

**Issue by steckes** [JamesHallowell/cxx-juce#4]
Thank you, the engine and the build works great! :)

I try to integrate the components into a struct to add a callback to the manager and delete it later like this: 

```Rust
pub struct Audio<'a> {
    pub device_manager: AudioDeviceManager<'a>,
    pub handle: Option<AudioCallbackHandle<'a>>,
}

impl<'a> Audio<'a> {
    pub fn add_callback(&mut self, callback: impl AudioIODeviceCallback + 'static) {
        self.handle = Some(self.device_manager.add_audio_callback(callback));
    }

    pub fn remove_callback(&mut self) {
        self.handle = None;
    }
}
```

This leads the error message:

```Rust
1 | impl<'a> Audio<'a> {
  |      -- lifetime `'a` defined here
2 |     pub fn add_callback(&mut self, callback: impl AudioIODeviceCallback + 'static) {
  |                         - let's call the lifetime of this reference `'1`
3 |         self.handle = Some(self.device_manager.add_audio_callback(callback));
  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ argument requires that `'1` must outlive `'a`
```

I tried a lot of different options so far, the only thing that I can make work is to store the handle directly in the main and not change it anymore. Have you ever tried to store the handle somewhere and change it later?

Best,
Stephan

**Comment by JamesHallowell** [comment]
>Thank you, the engine and the build works great! :)

Excellent, I'm glad to hear!
 
> I try to integrate the components into a struct to add a callback to the manager and delete it later like this:
> 
> ```rust
> pub struct Audio<'a> {
>     pub device_manager: AudioDeviceManager<'a>,
>     pub handle: Option<AudioCallbackHandle<'a>>,
> }
> 
> impl<'a> Audio<'a> {
>     pub fn add_callback(&mut self, callback: impl AudioIODeviceCallback + 'static) {
>         self.handle = Some(self.device_manager.add_audio_callback(callback));
>     }
> 
>     pub fn remove_callback(&mut self) {
>         self.handle = None;
>     }
> }
> ```
> 
> This leads the error message:
> 
> ```rust
> 1 | impl<'a> Audio<'a> {
>   |      -- lifetime `'a` defined here
> 2 |     pub fn add_callback(&mut self, callback: impl AudioIODeviceCallback + 'static) {
>   |                         - let's call the lifetime of this reference `'1`
> 3 |         self.handle = Some(self.device_manager.add_audio_callback(callback));
>   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ argument requires that `'1` must outlive `'a`
> ```

Interesting, I hadn't tried something like that before but it makes sense to do so! I think here it might be hitting into a variant of [this issue with storing a value and a reference to that value in the same struct](https://stackoverflow.com/a/32300133).

In the `Audio` struct I think there are two different lifetimes in play:

```rust
pub struct Audio<'juce, 'device_manager> {
    pub device_manager: AudioDeviceManager<'juce>,
    pub handle: Option<AudioCallbackHandle<'device_manager>>,
}
```

- The `AudioDeviceManager` is tied to a `'juce` lifetime since it relies on all the JUCE message machinery being setup.
- The `AudioCallbackHandle` has a lifetime that is tied to the `'device_manager`, since it borrows the `AudioDeviceManager` in order to later remove the callback when it gets dropped.

This means the `handle` field borrows from the `device_manager` field, which I think makes the `Audio` struct self-referential in some sense.

It's possible to temporarily "satisfy" the compiler by doing something like:

```rust
pub struct Audio<'juce, 'device_manager> {
    pub device_manager: AudioDeviceManager<'juce>,
    pub handle: Option<AudioCallbackHandle<'device_manager>>,
}

impl<'juce, 'device_manager> Audio<'juce, 'device_manager> {
    pub fn add_callback<'this>(&'this mut self, callback: impl AudioIODeviceCallback + 'static)
    where
        'this: 'device_manager,
    {
        self.handle = Some(self.device_manager.add_audio_callback(callback));
    }

    pub fn remove_callback(&mut self) {
        self.handle = None;
    }
}
```

But this isn't actually useful since the borrow checker will get upset later on when we try to actually call `add_callback` (see the "**A type with a reference to itself**" section of the linked StackOverflow answer).

>I tried a lot of different options so far, the only thing that I can make work is to store the handle directly in the main and not change it anymore. Have you ever tried to store the handle somewhere and change it later?

I'll have a look at some of the code I wrote using this crate to see how this was being dealt with.

I agree this feels like a reasonable thing to want to do, but the lifetimes in play make this awkward (or even not possible currently?). There is probably something that could be done to make this more ergonomic, I'll have a think.

**Comment by steckes** [comment]
Sounds good! I would have some more workarounds in mind, but they would be over-complicated.
I invited you to my private juce-wrapper that I started some years ago, if you want to have a look at it. There I don't need any lifetimes, but I currently have some build problems.

**Comment by JamesHallowell** [comment]
> Sounds good! I would have some more workarounds in mind, but they would be over-complicated. I invited you to my private juce-wrapper that I started some years ago, if you want to have a look at it. There I don't need any lifetimes, but I currently have some build problems.

Oh nice, thanks! I'll take a look.

**Comment by JamesHallowell** [comment]
Hey @steckes, just published 0.7 which hopefully resolves this issue. The code you posted might now look something like this:

```rust
pub struct Audio<'juce> {
    pub device_manager: AudioDeviceManager<'juce>,
    pub handle: Option<AudioCallbackHandle>,
}

impl<'juce> Audio<'juce> {
    pub fn add_callback(&mut self, callback: impl AudioIODeviceCallback + 'static) {
        self.remove_callback();
        self.handle = Some(self.device_manager.add_audio_callback(callback));
    }

    pub fn remove_callback(&mut self) {
        if let Some(handle) = self.handle.take() {
            self.device_manager.remove_audio_callback(handle);
        }
    }
}
```

**Comment by steckes** [comment]
Yay, so fast! I will test it later today :)

**Comment by steckes** [comment]
Works like a charm now, thank you very much!
